title: Dashpipe Docs
description: Documentation for the Dashpipe open-source pipeline platform
permalink: /:path.html
markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
